version: '3.9'

services:
  db:
    image: supabase/postgres:15.1.0.46-rc0
    container_name: vadeonibus-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vadeonibus-backend
    depends_on:
      - db
    environment:
      # example envs for connecting to Postgres
      DATABASE_HOST: ${DB_HOST}
      DATABASE_PORT: 5432
      DATABASE_USER: ${DB_USER}
      DATABASE_PASSWORD: ${DB_PASSWORD}
      DATABASE_NAME: ${DB_NAME}
      API_TIMEZONE: ${API_TIMEZONE}
      CATCHUP_HOURS: ${CATCHUP_HOURS}

      
    ports:
      - "${BACKEND_PORT}:3001"

volumes:
  db_data:
