version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vadeonibus-backend
    environment:
      # Database connection
      DATABASE_HOST: ${DB_HOST}
      DATABASE_PORT: ${DB_PORT}
      DATABASE_USER: ${DB_USER}
      DATABASE_PASSWORD: ${DB_PASSWORD}
      DATABASE_NAME: ${DB_NAME}
      
     
      # Rio config
      CATCHUP_HOURS: ${CATCHUP_HOURS}
      MAX_SNAP_DISTANCE_METERS: ${MAX_SNAP_DISTANCE_METERS}
      TERMINAL_PASSAGE_DISTANCE_METERS: ${TERMINAL_PASSAGE_DISTANCE_METERS}
      TERMINAL_PROXIMITY_DISTANCE_METERS: ${TERMINAL_PROXIMITY_DISTANCE_METERS}
      PROXIMITY_WINDOW_MINUTES: ${PROXIMITY_WINDOW_MINUTES}
      PROXIMITY_MIN_DURATION_MINUTES: ${PROXIMITY_MIN_DURATION_MINUTES}
      RIO_POLLING_WINDOW_MINUTES: ${RIO_POLLING_WINDOW_MINUTES}


      # Angra config
      ANGRA_SSX_USERNAME: ${ANGRA_SSX_USERNAME}
      ANGRA_SSX_PASSWORD: ${ANGRA_SSX_PASSWORD}
      ANGRA_SSX_CLIENT_CODE: ${ANGRA_SSX_CLIENT_CODE}
      ANGRA_SSX_TOKEN_REFRESH_MS: ${ANGRA_SSX_TOKEN_REFRESH_MS}
      

      # Sentido & Reports
      SENTIDO_BATCH_SIZE: ${SENTIDO_BATCH_SIZE}
      DB_BATCH_SIZE: ${DB_BATCH_SIZE}

      # api
      API_BASE_PATH: ${API_BASE_PATH}
      AUTH_USERNAME: ${AUTH_USERNAME}
      AUTH_PASSWORD: ${AUTH_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}

      # Timezone 
      API_TIMEZONE: ${API_TIMEZONE}
      
      # Logs 
      JOB_LOG_RETENTION_DAYS: ${JOB_LOG_RETENTION_DAYS}
      PROXIMITY_EVENT_RETENTION_HOURS: ${PROXIMITY_EVENT_RETENTION_HOURS}
    ports:
      - "${BACKEND_PORT}:3001"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vadeonibus-frontend
    environment:
      PUBLIC_BACKEND_URL: ${BACKEND_URL}
      PUBLIC_JOB_LOG_RETENTION_DAYS: ${JOB_LOG_RETENTION_DAYS}
    ports:
      - "5173:5173"

volumes:
  db_data:
